### ISSUE TITLE
Add migrations status with each entry in goose_migrations

### ISSUE THREAD

**Issue by sasidhar** [leantaas/postgoose#17]
We should have more status information with each entry in `goose_migrations`

Currently we are not tracking the following

* The status of current migration. Maybe something like: `applying_up`, `applying_down`, `applying_up_success`, `applying_down_success`, `applying_up_failed`, `applying_down_failed` etc.

* If there are any errors happened, we are not storing, what the error is. We should start storing these errors for later debugging purposes.

* Also, if possible, how about storing the time taken to run any migration. In case of multi-tenants, this information helps us understand the performance of each migration.

**Comment by dravidjoseph** [comment]
This has been addressed in 0.1.1 and we can close this issue.
